[package]
name = "mev-protection-guardian"
version = "0.1.0"
edition = "2021"
description = "Shielding transactions from the sandwich spirits"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait = "0.1"
ethers = "2.0"
hex = "0.4"
sha3 = "0.10"
rand = "0.8"

[dev-dependencies]
tokio-test = "0.4"
